### ISSUE TITLE
v1.1.0 breaks semver compatibility

### ISSUE THREAD

**Issue by andreyluchin** [jpillora/ipfilter#12]
I have some code that depends on `ipfilter` module and noticed that 1.1.0 breaks compatibility when it definitely [must not](https://github.com/golang/go/wiki/Modules#modules).

`ipfilter.NewNoDB`  seems to exist in 1.0.0 but not in 1.1.0. There might be other breaking changes I haven't noticed yet.

Please, either restore compatibility in 1.1 or bump the version to 2.0

**Comment by jpillora** [comment]
Ah very true, will restore compatibility though I’ll make all of those APIs
no-ops. Acquiring a MaxmindDB is too onerous.

**Comment by jpillora** [comment]
Published `v1.2.1`
