### ISSUE TITLE
How allow/deny access by the host

### ISSUE THREAD

**Issue by IgorN** [jpillora/ipfilter#5]
hi!

func handle(w http.ResponseWriter, r *http.Request) {
	fmt.Fprint(w, "Metrix")
}

http.HandleFunc("/metrics", handle)  - how can I allow this host(for example) for some ip's ?

Thanks!

**Comment by jpillora** [comment]
```go
h := http.HandlerFunc(func handle(w http.ResponseWriter, r *http.Request) {
   fmt.Fprint(w, "Metrix")
})

h = ipfilter.Wrap(h, ipfilter.Options{  ...  })

http.HandleFunc("/metrics", h)
```
```
